BEGIN = "<!-- BEGIN AUTOGENERATED !-->\n```bash\n"
END = "\n```\n<!-- END AUTOGENERATED !-->"

import subprocess

compressed = subprocess.check_output(["sh", "compress.sh"]).decode()

with open("README.md") as f:
    readme = f.read()

replace = BEGIN + compressed + END

start_ind = readme.find(BEGIN)
end_ind = readme.find(END) + len(END)

readme = readme[:start_ind] + replace + readme[end_ind:]

with open("README.md", "w") as f:
    f.write(readme)
